
CREATE TABLE IF NOT EXISTS SCHOOL (
    STUDENT_ID TEXT,
    NAME TEXT,
    SCHOOLBRANCH_ID TEXT,
    PRINCIPAL_ID TEXT,
    SCORE REAL
);
INSERT INTO SCHOOL (STUDENT_ID, NAME, SCHOOLBRANCH_ID, PRINCIPAL_ID, SCORE) VALUES
('100', 'STEVEN KING', '90', '100', 24000),
('101', 'NEENA KOCHCAR', '90', '100', 17000),
('102', 'LEX DEHAAN', '90', '102', 9000),
('103', 'BRUCE LEE', '60', '103', 4800),
('104', 'DIANA WILLS', '60', '103', 25000),
('105', 'VALLI PATOR', '50', '100', 4200),
('1973', 'LUV HAMI', '60', '102', 5000),
('106', 'DAVID AUSTIN', '90', '100', 6000);
SELECT SCHOOLBRANCH_ID AS "Branch Code",
       COUNT(*) AS "No of Students"
FROM SCHOOL
GROUP BY SCHOOLBRANCH_ID;
SELECT SCHOOLBRANCH_ID,
       SUM(SCORE)
FROM SCHOOL
GROUP BY SCHOOLBRANCH_ID;
SELECT SCHOOLBRANCH_ID AS "Branch Code",
       COUNT(*) AS "No of Students",
       SUM(SCORE) AS "Total Score"
FROM SCHOOL
GROUP BY SCHOOLBRANCH_ID;
SELECT SCHOOLBRANCH_ID AS "Branch Code",
       SUM(SCORE) AS "Total Score"
FROM SCHOOL
WHERE PRINCIPAL_ID = '103'
GROUP BY SCHOOLBRANCH_ID;
SELECT SCHOOLBRANCH_ID,
       COUNT(*) AS "No. of Students"
FROM SCHOOL
GROUP BY SCHOOLBRANCH_ID
HAVING COUNT(*) > 2;